language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  # remove docker-compose
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose

  # install docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # install kubectl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

install:
  - ls -al
  - cd udacity-c3-frontend
  - ls -al
  - npm run build
  - cd -
  - cd udacity-c3-restapi-feed/
  - npm run build
  - cd -
  - cd udacity-c3-restapi-user/
  - ls -al
  - npm run build
  - cd -
  - cd udacity-c3-deployment/docker
  - ls -al
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker-compose -f docker-compose-build.yaml push